// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://difkvzychmomhjqtxwdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZmt2enljaG1vbWhqcXR4d2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzg5NTgsImV4cCI6MjA3Mzk1NDk1OH0.qb_6LKMUlTv-_u_sqU14383Ph915JecBkyKN_iy4xZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});